#!/bin/bash
set -eo pipefail

pharod="$(command -v pharod)"
if [[ -z $pharod ]]; then
  echo "pharod not found in \$PATH, please check it's installed properly"
  exit 1
fi

if pgrep -qx pharod; then
  echo "You can only have one instance of pharod running at one time"
  exit 1
fi

if command -v dlite >/dev/null; then
  if ! pgrep -qx dlite; then
    echo "dlite not running, please start it with 'dlite start'"
    exit 1
  fi

  if ! grep -qw '^local.docker ' ~/.ssh/known_hosts; then
    ssh-keyscan -t rsa local.docker 2>/dev/null >>~/.ssh/known_hosts
  fi

  if [[ -z $DOCKER_FIRST_EPHEMERAL_PORT ]]; then
    # This is what Docker also reads the first port from.
    DOCKER_FIRST_EPHEMERAL_PORT="$(ssh docker@local.docker cat /proc/sys/net/ipv4/ip_local_port_range | egrep -o '^\d+')"
  fi

elif [[ $(uname -s) == "Darwin" ]]; then
  echo "To use Docker in OS X, you need to install https://github.com/nlf/dlite"
  exit 1
fi

args=""

if [[ -z $PHAROD_FOREGROUND ]]; then
  args="$args -d"
fi

exec sudo sh -c "DOCKER_HOST='unix:///var/run/docker.sock' DOCKER_HOST_IP='local.docker' DOCKER_FIRST_EPHEMERAL_PORT='$DOCKER_FIRST_EPHEMERAL_PORT' '$pharod' $args"
